name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    
    # Zip the dist folder
    - name: Zip dist folder
      run: zip -r dist-${{ matrix.node-version }}.zip dist

    # Upload the zip file as an artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist-${{ matrix.node-version }}
        path: dist-${{ matrix.node-version }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4
  
      # Download artifacts from the previous job
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts
  
      # Create a new tag
      - name: Create Tag
        id: tag_version
        run: |
          TAG_NAME=v1.0.${{ github.run_number }}
          echo "tag_name=$TAG_NAME" >> $GITHUB_ENV

      # Push the tag to the repository
      - name: Push Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag ${{ env.tag_name }}
          git push origin ${{ env.tag_name }}

      # Create a GitHub Release and upload artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.tag_name }}
          files: artifacts/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
